# Generated by Django 4.2.1 on 2023-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_technology_usernet_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='technology',
            field=models.ManyToManyField(null=True, related_name='users', to='profiles.technology'),
        ),
    ]
