# Generated by Django 4.2.1 on 2023-07-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(default='asdf', upload_to='group/avatar'),
            preserve_default=False,
        ),
    ]
